transit:
  t0: 0.0
  per: 2.21857567
  rp: 0.1548291121
  a: 8.9625402483
  inc: 85.71
  ecc: 0.0
  w: 20.0
  u: [0.1, 0.3]
  limb_dark: "quadratic"

classifier:
  type: cnn

cnn:
  dataset_path: /ca25/comp_astro25/tess_data.csv
  result_dir: /ca25/comp_astro25/cnn_results
  n_bins: 1000
  samples_per_class: 350
  learning_rate: 0.0001
  kernel_size: 3
  epochs: 200
  
